// File: lib/features/auth/services/auth_service.dart

import 'package:flutter_appauth/flutter_appauth.dart';
import 'package:frontend/core/config/env_config.dart';
import 'package:frontend/features/auth/models/auth_failure.dart';
import 'package:frontend/features/auth/models/auth_method.dart';
import 'package:frontend/features/auth/models/auth_session_model.dart';

/// The only file in the project that imports `flutter_appauth`.
///
/// Handles three operations:
/// 1. [signIn]        — PKCE authorization code flow (in-app browser).
/// 2. [refreshTokens] — Silent token refresh (no browser).
/// 3. [endSession]    — Keycloak end-session (clears SSO cookie).
class AuthService {
  final FlutterAppAuth _appAuth;

  AuthService({FlutterAppAuth? appAuth})
      : _appAuth = appAuth ?? const FlutterAppAuth();

  // ── Sign In ──

  /// Launches the in-app browser for PKCE authorization.
  ///
  /// [method] determines the Keycloak `additionalParameters`:
  /// - Google:  `kc_idp_hint=google` → Keycloak redirects straight to Google
  /// - Email:   `kc_idp_hint=` (empty) + `acr_values=otp`
  /// - Passkey: `acr_values=passkey`
  ///
  /// Returns an [AuthSessionModel] on success.
  /// Throws an [AuthFailure] subtype on failure.
  Future<AuthSessionModel> signIn(AuthMethod method, {String? loginHint}) async {
    final params = switch (method) {
      AuthMethod.google => {'kc_idp_hint': 'google'},
      AuthMethod.email => {'kc_idp_hint': '', 'acr_values': 'otp'},
      AuthMethod.passkey => {'acr_values': 'passkey'},
    };

    try {
      final result = await _appAuth.authorizeAndExchangeCode(
        AuthorizationTokenRequest(
          EnvConfig.keycloakClientId,
          EnvConfig.keycloakRedirectUri,
          issuer: EnvConfig.keycloakIssuer,
          scopes: EnvConfig.keycloakScopes,
          additionalParameters: params,
          promptValues: const ['login'], // Force re-auth, skip SSO session
          loginHint: loginHint,
          // PKCE (S256) + state are auto-generated by the plugin.
        ),
      );

      return _mapTokenResponse(result, method);
    } on AuthFailure {
      rethrow;
    } catch (e) {
      throw _mapPlatformException(e);
    }
  }

  // ── Token Refresh ──

  /// Performs a silent token refresh using the stored refresh token.
  ///
  /// This method calls Keycloak's token endpoint directly — it does NOT
  /// go through [ApiClient], so there is no circular dependency.
  Future<AuthSessionModel> refreshTokens(
    String refreshToken,
    AuthMethod method,
  ) async {
    try {
      final result = await _appAuth.token(
        TokenRequest(
          EnvConfig.keycloakClientId,
          EnvConfig.keycloakRedirectUri,
          issuer: EnvConfig.keycloakIssuer,
          refreshToken: refreshToken,
          scopes: EnvConfig.keycloakScopes,
        ),
      );

      return _mapTokenResponse(result, method);
    } on AuthFailure {
      rethrow;
    } catch (e) {
      throw const AuthFailureRefreshFailed();
    }
  }

  // ── End Session ──

  /// Hits Keycloak's end-session endpoint to revoke the refresh token
  /// and clear the SSO cookie in the in-app browser.
  Future<void> endSession(String idToken) async {
    try {
      await _appAuth.endSession(
        EndSessionRequest(
          idTokenHint: idToken,
          postLogoutRedirectUrl: EnvConfig.keycloakPostLogoutRedirectUri,
          issuer: EnvConfig.keycloakIssuer,
        ),
      );
    } catch (_) {
      // End-session failures are non-critical — the local session is
      // cleared regardless, and the refresh token will expire naturally.
    }
  }

  // ── Helpers ──

  AuthSessionModel _mapTokenResponse(
    TokenResponse result,
    AuthMethod method,
  ) {
    final accessToken = result.accessToken;
    final refreshToken = result.refreshToken;

    if (accessToken == null || refreshToken == null) {
      throw const AuthFailureUnknown('Incomplete token response from Keycloak.');
    }

    // Compute absolute expiry from the relative `expiresIn` or the
    // `accessTokenExpirationDateTime` provided by the plugin.
    final expiresAt = result.accessTokenExpirationDateTime ??
        DateTime.now().add(const Duration(minutes: 5)); // Keycloak default

    return AuthSessionModel(
      accessToken: accessToken,
      refreshToken: refreshToken,
      idToken: result.idToken,
      expiresAt: expiresAt,
      method: method,
    );
  }

  AuthFailure _mapPlatformException(Object error) {
    final message = error.toString().toLowerCase();

    // flutter_appauth throws PlatformException with specific codes/messages
    // when the user cancels the browser.
    if (message.contains('cancel') ||
        message.contains('user_cancelled') ||
        message.contains('null')) {
      return const AuthFailureCancelled();
    }
    if (message.contains('network') || message.contains('connection')) {
      return AuthFailureNetwork(error.toString());
    }
    return AuthFailureUnknown(error.toString());
  }

}

